# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/streamlit-repo/insurance-analyzer', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/streamlit-repo/insurance-analyzer']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'insurance-analyzer',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/streamlit-repo/insurance-analyzer',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8501'
      ]
